version: "6.0"

experiment:
  UMI: yes
  SNP: yes

scripts:
  location: path/to/scripts/perl
  #UMI_script: NA -- same as SNP script
  SNP_script: ast_snpv72.pl
  asymagic: as2.pl
  s2: step2v56.pl

output:
#### step 2 only:
  result: output/test_out.txt
  ## the following line should be uncommented if you don't want this YAML file copied to output
  #~ output_yaml: no

# if DEBUG: 1 -- diagnostic info will be printed after each gene
diagnostics:
  DEBUG: 1
  use_existing_sorted_SAM: 0
  leave_SAM: 1
  #~ SAMsubsampleFraction: 05
  ##[01..99] ^ for debug purposes only!  for real analysis: comment it out!
  ## In step2.pl defines % of BAM to subsample. Useful for a speedup when testing
  ##

alignment:
#file_names:
  ### the following applies to step 1:::
  fastq_dir: /path/to/fastq/
  R1: R1.fastq
  R2: R2.fastq
  reference: mm10
  ### the following applies to step 1 + step 2:::
  SAM_name_base: example_mm10
  SAM_location: sam/example/
  
#### Description of targets (step2)
genes:
  AdNp2:
    SNP: TCCCTG[N/N]CAGCTA
    position: chr18:80125935-80128475
#~ SKIP:    
  Adamtsl4:
    SNP: GGGGAA[N/N]GACCAC
    position: chr3:95675004-95677646
  Dlc1:
    SNP: AAGAAC[N/N]GAGCAA
    position: chr8:36566539-36569311
  DNajc12:
    SNP: CAAAAT[N/N]TAGACT
    position: chr10:63407514-63410040
  Gprasp1:
    SNP: ACGCTT[N/N]TTGTGT
    position: chrX:135802055-135804668
  SmtNl2:
    SNP: ATTTCT[N/N]TGTGGG
    position: chr11:72388914-72391598
  3830406C13Rik:
    SNP: TAAGCC[N/N]GAAGAT
    position: chr14:12301702-12304431
  Slc25a37:
    SNP: TATGAA[N/N]AACAAA
    position: chr14:69240651-69243339
  Tpst1:
    SNP: TTGAAG[N/N]TGGCAT
    position: chr5:130134244-130136932


samples_barcodes:
  aNA_NA_5_DBJ28_R1_d12: AGTCAA_GTGAAA
  bKdm1a_CDS_1_DBJ28_R1_d12: AGTTCC_GTGGCC
  cCbx3_CDS_1_DBJ28_R1_d12: ATGTCA_GTTTCG
  dClspn_CDS_1_DBJ28_R1_d12: CCGTCC_CGTACG
  eJarid2_CDS_1_DBJ28_R1_d12: GTAGAG_GAGTGG
  fDnmt3a_CDS_1_DBJ28_R1_d12: GTCCGC_GGTAGC
  gCul3_3UTR_1_DBJ28_R1_d12: GTGAAA_AGTCAA
  hAurka_CDS_1_DBJ28_R1_d12: GTGGCC_AGTTCC
  iBmpr2_CDS_1_DBJ28_R1_d12: GTTTCG_ATGTCA
  jKdm1a_CDS_2_DBJ28_R1_d12: CGTACG_CCGTCC
  kAsh2l_3UTR_1_DBJ28_R1_d12: GAGTGG_GTAGAG
  lAsh2l_CDS_2_DBJ28_R1_d12: GGTAGC_GTCCGC
  mDnmt3a_CDS_2_DBJ28_R1_d12: AGTCAA_CACGAT
  nAcvr1_CDS_1_DBJ28_R1_d12: AGTTCC_CACTCA
  oGins3_CDS_1_DBJ28_R1_d12: ATGTCA_CAGGCG
  pCdyl_CDS_1_DBJ28_R1_d12: CCGTCC_CATGGC
  qClspn_3UTR_2_DBJ28_R1_d12: GTAGAG_CATTTT
  rBrca2_CDS_1_DBJ28_R1_d12: GTCCGC_CCAACA
  sBmpr2_CDS_2_DBJ28_R1_d12: GTGAAA_ACTGAT
  tCul3_CDS_2_DBJ28_R1_d12: GTGGCC_ATGAGC
  uHdac3_3UTR_1_DBJ28_R1_d12: GTTTCG_ATTCCT
  vAcvr1b_CDS_1_DBJ28_R1_d12: CGTACG_CAAAAG
  wHdac3_CDS_2_DBJ28_R1_d12: GAGTGG_CAACTA
  xCbx3_CDS_2_DBJ28_R1_d12: GGTAGC_CACCGG
  yFbxo8_CDS_1_DBJ28_R1_d12: AGTCAA_TACAGC
  zJarid2_CDS_2_DBJ28_R1_d12: AGTTCC_TATAAT
  aaBmpr2_CDS_3_DBJ28_R1_d12: ATGTCA_TCATTC
  abDnmt3a_CDS_3_DBJ28_R1_d12: CCGTCC_TCCCGA
  acJarid2_CDS_3_DBJ28_R1_d12: GTAGAG_TCGAAG
  adAurka_CDS_2_DBJ28_R1_d12: GTCCGC_TCGGCA
  aeCul3_CDS_3_DBJ28_R1_d12: GTGAAA_CGGAAT
#~ SKIP:  
  afLUCIFERASE_CDS_4_DBJ28_R1_d12: GTGGCC_CTAGCT
  agAcvr1b_CDS_2_DBJ28_R1_d12: GTTTCG_CTATAC
  ahAurka_CDS_3_DBJ28_R1_d12: CGTACG_CTCAGA
  aiAsh2l_CDS_3_DBJ28_R1_d12: GAGTGG_GACGAC
  ajGins3_CDS_2_DBJ28_R1_d12: GGTAGC_TAATCG
  akCbx3_CDS_3_DBJ28_R1_d12: ACTGAT_GTGAAA
  alCdyl_CDS_2_DBJ28_R1_d12: ATGAGC_GTGGCC
  amBrca2_CDS_2_DBJ28_R1_d12: ATTCCT_GTTTCG
  anAff1_CDS_1_DBJ28_R1_d12: CAAAAG_CGTACG
  aoAcvr1_CDS_2_DBJ28_R1_d12: CAACTA_GAGTGG
  apHdac3_CDS_3_DBJ28_R1_d12: CACCGG_GGTAGC
  aqAcvr1b_CDS_3_DBJ28_R1_d12: CACGAT_AGTCAA
  arBmpr2_CDS_4_DBJ28_R1_d12: CACTCA_AGTTCC
  asGFP_CDS_4_DBJ28_R1_d12: CAGGCG_ATGTCA
  atCdyl_3UTR_3_DBJ28_R1_d12: CATGGC_CCGTCC
  auAcvr1_CDS_3_DBJ28_R1_d12: CATTTT_GTAGAG
  avClspn_3UTR_3_DBJ28_R1_d12: CCAACA_GTCCGC
  awH2afy_CDS_1_DBJ28_R1_d12: ACTGAT_CACGAT
  axJarid2_CDS_4_DBJ28_R1_d12: ATGAGC_CACTCA
  ayGins3_CDS_3_DBJ28_R1_d12: ATTCCT_CAGGCG
  azCbx3_3UTR_4_DBJ28_R1_d12: CAAAAG_CATGGC
  baHdac3_CDS_4_DBJ28_R1_d12: CAACTA_CATTTT
  bbCul3_CDS_4_DBJ28_R1_d12: CACCGG_CCAACA
  bcKdm1a_CDS_3_DBJ28_R1_d12: CACGAT_ACTGAT
  bdBrca2_CDS_3_DBJ28_R1_d12: CACTCA_ATGAGC
  beAff1_CDS_2_DBJ28_R1_d12: CAGGCG_ATTCCT
  bfClspn_CDS_4_DBJ28_R1_d12: CATGGC_CAAAAG
  bgHdac3_CDS_5_DBJ28_R1_d12: CATTTT_CAACTA
  bhAcvr1_CDS_4_DBJ28_R1_d12: CCAACA_CACCGG
  biH2afy_CDS_2_DBJ28_R1_d12: ACTGAT_TACAGC
  bjCbx3_CDS_5_DBJ28_R1_d12: ATGAGC_TATAAT
  bkKdm1a_CDS_4_DBJ28_R1_d12: ATTCCT_TCATTC
  blDnmt3a_CDS_4_DBJ28_R1_d12: CAAAAG_TCCCGA
  bmCdyl_CDS_4_DBJ28_R1_d12: CAACTA_TCGAAG
  bnAff1_CDS_3_DBJ28_R1_d12: CACCGG_TCGGCA
  boH2afy_CDS_3_DBJ28_R1_d12: CACGAT_CGGAAT
  bpCdyl_CDS_5_DBJ28_R1_d12: CACTCA_CTAGCT
  bqJarid2_3UTR_5_DBJ28_R1_d12: CAGGCG_CTATAC
  brAcvr1b_CDS_4_DBJ28_R1_d12: CATGGC_CTCAGA
  bsDnmt3a_CDS_5_DBJ28_R1_d12: CATTTT_GACGAC
  btAff1_3UTR_4_DBJ28_R1_d12: CCAACA_TAATCG
  buGins3_CDS_4_DBJ28_R1_d12: CGGAAT_GTGAAA
  bvAff1_CDS_5_DBJ28_R1_d12: CTAGCT_GTGGCC
  bwH2afy_CDS_4_DBJ28_R1_d12: CTATAC_GTTTCG
  bxAcvr1b_CDS_5_DBJ28_R1_d12: CTCAGA_CGTACG
  byBmpr2_3UTR_5_DBJ28_R1_d12: GACGAC_GAGTGG
  bzFbxo8_CDS_2_DBJ28_R1_d12: TAATCG_GGTAGC
  caAsh2l_CDS_4_DBJ28_R1_d12: TACAGC_AGTCAA
  cbAurka_CDS_4_DBJ28_R1_d12: TATAAT_AGTTCC
  ccKdm1a_CDS_5_DBJ28_R1_d12: TCATTC_ATGTCA
  cdAsh2l_CDS_5_DBJ28_R1_d12: TCCCGA_CCGTCC
  ceFbxo8_CDS_3_DBJ28_R1_d12: TCGAAG_GTAGAG
  cfFbxo8_3UTR_4_DBJ28_R1_d12: TCGGCA_GTCCGC
  cgClspn_CDS_5_DBJ28_R1_d12: CGGAAT_CACGAT
  chCul3_CDS_5_DBJ28_R1_d12: CTAGCT_CACTCA
  ciFbxo8_CDS_5_DBJ28_R1_d12: CTATAC_CAGGCG
  cjBrca2_3UTR_4_DBJ28_R1_d12: CTCAGA_CATGGC
  ckAcvr1_CDS_5_DBJ28_R1_d12: GACGAC_CATTTT
  clAurka_CDS_5_DBJ28_R1_d12: TAATCG_CCAACA
  cmBrca2_CDS_5_DBJ28_R1_d12: TACAGC_ACTGAT
  cnGins3_3UTR_5_DBJ28_R1_d12: TATAAT_ATGAGC
  coNA_NA_6_DBJ28_R1_d12: TCATTC_ATTCCT
  cpNA_NA_7_DBJ28_R1_d12: TCCCGA_CAAAAG
  cqH2afy_CDS_5_DBJ28_R1_d12: TCGAAG_CAACTA
  crNA_NA_8_DBJ28_R1_d12: TCGGCA_CACCGG
  aNA_NA_5_DBJ28_R2_d12: AGTCAA_AGTCAA
  bKdm1a_CDS_1_DBJ28_R2_d12: AGTTCC_AGTTCC
  cCbx3_CDS_1_DBJ28_R2_d12: ATGTCA_ATGTCA
  dClspn_CDS_1_DBJ28_R2_d12: CCGTCC_CCGTCC
  eJarid2_CDS_1_DBJ28_R2_d12: GTAGAG_GTAGAG
  fDnmt3a_CDS_1_DBJ28_R2_d12: GTCCGC_GTCCGC
  gCul3_3UTR_1_DBJ28_R2_d12: GTGAAA_GTGAAA
  hAurka_CDS_1_DBJ28_R2_d12: GTGGCC_GTGGCC
  iBmpr2_CDS_1_DBJ28_R2_d12: GTTTCG_GTTTCG
  jKdm1a_CDS_2_DBJ28_R2_d12: CGTACG_CGTACG
  kAsh2l_3UTR_1_DBJ28_R2_d12: GAGTGG_GAGTGG
  lAsh2l_CDS_2_DBJ28_R2_d12: GGTAGC_GGTAGC
  mDnmt3a_CDS_2_DBJ28_R2_d12: AGTCAA_ACTGAT
  nAcvr1_CDS_1_DBJ28_R2_d12: AGTTCC_ATGAGC
  oGins3_CDS_1_DBJ28_R2_d12: ATGTCA_ATTCCT
  pCdyl_CDS_1_DBJ28_R2_d12: CCGTCC_CAAAAG
  qClspn_3UTR_2_DBJ28_R2_d12: GTAGAG_CAACTA
  rBrca2_CDS_1_DBJ28_R2_d12: GTCCGC_CACCGG
  sBmpr2_CDS_2_DBJ28_R2_d12: GTGAAA_CACGAT
  tCul3_CDS_2_DBJ28_R2_d12: GTGGCC_CACTCA
  uHdac3_3UTR_1_DBJ28_R2_d12: GTTTCG_CAGGCG
  vAcvr1b_CDS_1_DBJ28_R2_d12: CGTACG_CATGGC
  wHdac3_CDS_2_DBJ28_R2_d12: GAGTGG_CATTTT
  xCbx3_CDS_2_DBJ28_R2_d12: GGTAGC_CCAACA
  yFbxo8_CDS_1_DBJ28_R2_d12: AGTCAA_CGGAAT
  zJarid2_CDS_2_DBJ28_R2_d12: AGTTCC_CTAGCT
  aaBmpr2_CDS_3_DBJ28_R2_d12: ATGTCA_CTATAC
  abDnmt3a_CDS_3_DBJ28_R2_d12: CCGTCC_CTCAGA
  acJarid2_CDS_3_DBJ28_R2_d12: GTAGAG_GACGAC
  adAurka_CDS_2_DBJ28_R2_d12: GTCCGC_TAATCG
  aeCul3_CDS_3_DBJ28_R2_d12: GTGAAA_TACAGC
  afLUCIFERASE_CDS_4_DBJ28_R2_d12: GTGGCC_TATAAT
  agAcvr1b_CDS_2_DBJ28_R2_d12: GTTTCG_TCATTC
  ahAurka_CDS_3_DBJ28_R2_d12: CGTACG_TCCCGA
  aiAsh2l_CDS_3_DBJ28_R2_d12: GAGTGG_TCGAAG
  ajGins3_CDS_2_DBJ28_R2_d12: GGTAGC_TCGGCA
  akCbx3_CDS_3_DBJ28_R2_d12: ACTGAT_AGTCAA
  alCdyl_CDS_2_DBJ28_R2_d12: ATGAGC_AGTTCC
  amBrca2_CDS_2_DBJ28_R2_d12: ATTCCT_ATGTCA
  anAff1_CDS_1_DBJ28_R2_d12: CAAAAG_CCGTCC
  aoAcvr1_CDS_2_DBJ28_R2_d12: CAACTA_GTAGAG
  apHdac3_CDS_3_DBJ28_R2_d12: CACCGG_GTCCGC
  aqAcvr1b_CDS_3_DBJ28_R2_d12: CACGAT_GTGAAA
  arBmpr2_CDS_4_DBJ28_R2_d12: CACTCA_GTGGCC
  asGFP_CDS_4_DBJ28_R2_d12: CAGGCG_GTTTCG
  atCdyl_3UTR_3_DBJ28_R2_d12: CATGGC_CGTACG
  auAcvr1_CDS_3_DBJ28_R2_d12: CATTTT_GAGTGG
  avClspn_3UTR_3_DBJ28_R2_d12: CCAACA_GGTAGC
  awH2afy_CDS_1_DBJ28_R2_d12: ACTGAT_ACTGAT
  axJarid2_CDS_4_DBJ28_R2_d12: ATGAGC_ATGAGC
  ayGins3_CDS_3_DBJ28_R2_d12: ATTCCT_ATTCCT
  azCbx3_3UTR_4_DBJ28_R2_d12: CAAAAG_CAAAAG
  baHdac3_CDS_4_DBJ28_R2_d12: CAACTA_CAACTA
  bbCul3_CDS_4_DBJ28_R2_d12: CACCGG_CACCGG
  bcKdm1a_CDS_3_DBJ28_R2_d12: CACGAT_CACGAT
  bdBrca2_CDS_3_DBJ28_R2_d12: CACTCA_CACTCA
  beAff1_CDS_2_DBJ28_R2_d12: CAGGCG_CAGGCG
  bfClspn_CDS_4_DBJ28_R2_d12: CATGGC_CATGGC
  bgHdac3_CDS_5_DBJ28_R2_d12: CATTTT_CATTTT
  bhAcvr1_CDS_4_DBJ28_R2_d12: CCAACA_CCAACA
  biH2afy_CDS_2_DBJ28_R2_d12: ACTGAT_CGGAAT
  bjCbx3_CDS_5_DBJ28_R2_d12: ATGAGC_CTAGCT
  bkKdm1a_CDS_4_DBJ28_R2_d12: ATTCCT_CTATAC
  blDnmt3a_CDS_4_DBJ28_R2_d12: CAAAAG_CTCAGA
  bmCdyl_CDS_4_DBJ28_R2_d12: CAACTA_GACGAC
  bnAff1_CDS_3_DBJ28_R2_d12: CACCGG_TAATCG
  boH2afy_CDS_3_DBJ28_R2_d12: CACGAT_TACAGC
  bpCdyl_CDS_5_DBJ28_R2_d12: CACTCA_TATAAT
  bqJarid2_3UTR_5_DBJ28_R2_d12: CAGGCG_TCATTC
  brAcvr1b_CDS_4_DBJ28_R2_d12: CATGGC_TCCCGA
  bsDnmt3a_CDS_5_DBJ28_R2_d12: CATTTT_TCGAAG
  btAff1_3UTR_4_DBJ28_R2_d12: CCAACA_TCGGCA
  buGins3_CDS_4_DBJ28_R2_d12: CGGAAT_AGTCAA
  bvAff1_CDS_5_DBJ28_R2_d12: CTAGCT_AGTTCC
  bwH2afy_CDS_4_DBJ28_R2_d12: CTATAC_ATGTCA
  bxAcvr1b_CDS_5_DBJ28_R2_d12: CTCAGA_CCGTCC
  byBmpr2_3UTR_5_DBJ28_R2_d12: GACGAC_GTAGAG
  bzFbxo8_CDS_2_DBJ28_R2_d12: TAATCG_GTCCGC
  caAsh2l_CDS_4_DBJ28_R2_d12: TACAGC_GTGAAA
  cbAurka_CDS_4_DBJ28_R2_d12: TATAAT_GTGGCC
  ccKdm1a_CDS_5_DBJ28_R2_d12: TCATTC_GTTTCG
  cdAsh2l_CDS_5_DBJ28_R2_d12: TCCCGA_CGTACG
  ceFbxo8_CDS_3_DBJ28_R2_d12: TCGAAG_GAGTGG
  cfFbxo8_3UTR_4_DBJ28_R2_d12: TCGGCA_GGTAGC
  cgClspn_CDS_5_DBJ28_R2_d12: CGGAAT_ACTGAT
  chCul3_CDS_5_DBJ28_R2_d12: CTAGCT_ATGAGC
  ciFbxo8_CDS_5_DBJ28_R2_d12: CTATAC_ATTCCT
  cjBrca2_3UTR_4_DBJ28_R2_d12: CTCAGA_CAAAAG
  ckAcvr1_CDS_5_DBJ28_R2_d12: GACGAC_CAACTA
  clAurka_CDS_5_DBJ28_R2_d12: TAATCG_CACCGG
  cmBrca2_CDS_5_DBJ28_R2_d12: TACAGC_CACGAT
  cnGins3_3UTR_5_DBJ28_R2_d12: TATAAT_CACTCA
  coNA_NA_6_DBJ28_R2_d12: TCATTC_CAGGCG
  cpNA_NA_7_DBJ28_R2_d12: TCCCGA_CATGGC
  cqH2afy_CDS_5_DBJ28_R2_d12: TCGAAG_CATTTT
  crNA_NA_8_DBJ28_R2_d12: TCGGCA_CCAACA
  aNA_NA_5_DBJ28_R1_d19: AGTCAA_AGTTCC
  bKdm1a_CDS_1_DBJ28_R1_d19: AGTTCC_ATGTCA
  cCbx3_CDS_1_DBJ28_R1_d19: ATGTCA_CCGTCC
  dClspn_CDS_1_DBJ28_R1_d19: CCGTCC_GTAGAG
  eJarid2_CDS_1_DBJ28_R1_d19: GTAGAG_GTCCGC
  fDnmt3a_CDS_1_DBJ28_R1_d19: GTCCGC_GTGAAA
  gCul3_3UTR_1_DBJ28_R1_d19: GTGAAA_GTGGCC
  hAurka_CDS_1_DBJ28_R1_d19: GTGGCC_GTTTCG
  iBmpr2_CDS_1_DBJ28_R1_d19: GTTTCG_CGTACG
  jKdm1a_CDS_2_DBJ28_R1_d19: CGTACG_GAGTGG
  kAsh2l_3UTR_1_DBJ28_R1_d19: GAGTGG_GGTAGC
  lAsh2l_CDS_2_DBJ28_R1_d19: GGTAGC_AGTCAA
  mDnmt3a_CDS_2_DBJ28_R1_d19: AGTCAA_ATGAGC
  nAcvr1_CDS_1_DBJ28_R1_d19: AGTTCC_ATTCCT
  oGins3_CDS_1_DBJ28_R1_d19: ATGTCA_CAAAAG
  pCdyl_CDS_1_DBJ28_R1_d19: CCGTCC_CAACTA
  qClspn_3UTR_2_DBJ28_R1_d19: GTAGAG_CACCGG
  rBrca2_CDS_1_DBJ28_R1_d19: GTCCGC_CACGAT
  sBmpr2_CDS_2_DBJ28_R1_d19: GTGAAA_CACTCA
  tCul3_CDS_2_DBJ28_R1_d19: GTGGCC_CAGGCG
  uHdac3_3UTR_1_DBJ28_R1_d19: GTTTCG_CATGGC
  vAcvr1b_CDS_1_DBJ28_R1_d19: CGTACG_CATTTT
  wHdac3_CDS_2_DBJ28_R1_d19: GAGTGG_CCAACA
  xCbx3_CDS_2_DBJ28_R1_d19: GGTAGC_ACTGAT
  yFbxo8_CDS_1_DBJ28_R1_d19: AGTCAA_CTAGCT
  zJarid2_CDS_2_DBJ28_R1_d19: AGTTCC_CTATAC
  aaBmpr2_CDS_3_DBJ28_R1_d19: ATGTCA_CTCAGA
  abDnmt3a_CDS_3_DBJ28_R1_d19: CCGTCC_GACGAC
  acJarid2_CDS_3_DBJ28_R1_d19: GTAGAG_TAATCG
  adAurka_CDS_2_DBJ28_R1_d19: GTCCGC_TACAGC
  aeCul3_CDS_3_DBJ28_R1_d19: GTGAAA_TATAAT
  afLUCIFERASE_CDS_4_DBJ28_R1_d19: GTGGCC_TCATTC
  agAcvr1b_CDS_2_DBJ28_R1_d19: GTTTCG_TCCCGA
  ahAurka_CDS_3_DBJ28_R1_d19: CGTACG_TCGAAG
  aiAsh2l_CDS_3_DBJ28_R1_d19: GAGTGG_TCGGCA
  ajGins3_CDS_2_DBJ28_R1_d19: GGTAGC_CGGAAT
  akCbx3_CDS_3_DBJ28_R1_d19: ACTGAT_AGTTCC
  alCdyl_CDS_2_DBJ28_R1_d19: ATGAGC_ATGTCA
  amBrca2_CDS_2_DBJ28_R1_d19: ATTCCT_CCGTCC
  anAff1_CDS_1_DBJ28_R1_d19: CAAAAG_GTAGAG
  aoAcvr1_CDS_2_DBJ28_R1_d19: CAACTA_GTCCGC
  apHdac3_CDS_3_DBJ28_R1_d19: CACCGG_GTGAAA
  aqAcvr1b_CDS_3_DBJ28_R1_d19: CACGAT_GTGGCC
  arBmpr2_CDS_4_DBJ28_R1_d19: CACTCA_GTTTCG
  asGFP_CDS_4_DBJ28_R1_d19: CAGGCG_CGTACG
  atCdyl_3UTR_3_DBJ28_R1_d19: CATGGC_GAGTGG
  auAcvr1_CDS_3_DBJ28_R1_d19: CATTTT_GGTAGC
  avClspn_3UTR_3_DBJ28_R1_d19: CCAACA_AGTCAA
  awH2afy_CDS_1_DBJ28_R1_d19: ACTGAT_ATGAGC
  axJarid2_CDS_4_DBJ28_R1_d19: ATGAGC_ATTCCT
  ayGins3_CDS_3_DBJ28_R1_d19: ATTCCT_CAAAAG
  azCbx3_3UTR_4_DBJ28_R1_d19: CAAAAG_CAACTA
  baHdac3_CDS_4_DBJ28_R1_d19: CAACTA_CACCGG
  bbCul3_CDS_4_DBJ28_R1_d19: CACCGG_CACGAT
  bcKdm1a_CDS_3_DBJ28_R1_d19: CACGAT_CACTCA
  bdBrca2_CDS_3_DBJ28_R1_d19: CACTCA_CAGGCG
  beAff1_CDS_2_DBJ28_R1_d19: CAGGCG_CATGGC
  bfClspn_CDS_4_DBJ28_R1_d19: CATGGC_CATTTT
  bgHdac3_CDS_5_DBJ28_R1_d19: CATTTT_CCAACA
  bhAcvr1_CDS_4_DBJ28_R1_d19: CCAACA_ACTGAT
  biH2afy_CDS_2_DBJ28_R1_d19: ACTGAT_CTAGCT
  bjCbx3_CDS_5_DBJ28_R1_d19: ATGAGC_CTATAC
  bkKdm1a_CDS_4_DBJ28_R1_d19: ATTCCT_CTCAGA
  blDnmt3a_CDS_4_DBJ28_R1_d19: CAAAAG_GACGAC
  bmCdyl_CDS_4_DBJ28_R1_d19: CAACTA_TAATCG
  bnAff1_CDS_3_DBJ28_R1_d19: CACCGG_TACAGC
  boH2afy_CDS_3_DBJ28_R1_d19: CACGAT_TATAAT
  bpCdyl_CDS_5_DBJ28_R1_d19: CACTCA_TCATTC
  bqJarid2_3UTR_5_DBJ28_R1_d19: CAGGCG_TCCCGA
  brAcvr1b_CDS_4_DBJ28_R1_d19: CATGGC_TCGAAG
  bsDnmt3a_CDS_5_DBJ28_R1_d19: CATTTT_TCGGCA
  btAff1_3UTR_4_DBJ28_R1_d19: CCAACA_CGGAAT
  buGins3_CDS_4_DBJ28_R1_d19: CGGAAT_AGTTCC
  bvAff1_CDS_5_DBJ28_R1_d19: CTAGCT_ATGTCA
  bwH2afy_CDS_4_DBJ28_R1_d19: CTATAC_CCGTCC
  bxAcvr1b_CDS_5_DBJ28_R1_d19: CTCAGA_GTAGAG
  byBmpr2_3UTR_5_DBJ28_R1_d19: GACGAC_GTCCGC
  bzFbxo8_CDS_2_DBJ28_R1_d19: TAATCG_GTGAAA
  caAsh2l_CDS_4_DBJ28_R1_d19: TACAGC_GTGGCC
  cbAurka_CDS_4_DBJ28_R1_d19: TATAAT_GTTTCG
  ccKdm1a_CDS_5_DBJ28_R1_d19: TCATTC_CGTACG
  cdAsh2l_CDS_5_DBJ28_R1_d19: TCCCGA_GAGTGG
  ceFbxo8_CDS_3_DBJ28_R1_d19: TCGAAG_GGTAGC
  cfFbxo8_3UTR_4_DBJ28_R1_d19: TCGGCA_AGTCAA
  cgClspn_CDS_5_DBJ28_R1_d19: CGGAAT_ATGAGC
  chCul3_CDS_5_DBJ28_R1_d19: CTAGCT_ATTCCT
  ciFbxo8_CDS_5_DBJ28_R1_d19: CTATAC_CAAAAG
  cjBrca2_3UTR_4_DBJ28_R1_d19: CTCAGA_CAACTA
  ckAcvr1_CDS_5_DBJ28_R1_d19: GACGAC_CACCGG
  clAurka_CDS_5_DBJ28_R1_d19: TAATCG_CACGAT
  cmBrca2_CDS_5_DBJ28_R1_d19: TACAGC_CACTCA
  cnGins3_3UTR_5_DBJ28_R1_d19: TATAAT_CAGGCG
  coNA_NA_6_DBJ28_R1_d19: TCATTC_CATGGC
  cpNA_NA_7_DBJ28_R1_d19: TCCCGA_CATTTT
  cqH2afy_CDS_5_DBJ28_R1_d19: TCGAAG_CCAACA
  crNA_NA_8_DBJ28_R1_d19: TCGGCA_ACTGAT


step2:
#### Additional switches:
#### Do not change these unless you know what you are doing
 ## MAPQ=30 is high quality threshold
  minimal_MAPQ: 12
  LongReadSplitPattern: A7 A6 A18 A*
  ShortReadSplitPattern: A7 A6 A18 A11 A*
  T2_small: TCGCTAATTGC


